package com.myspace.zcp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("BIN Number")
    private java.lang.String BIN;
    @org.kie.api.definition.type.Label("Release Number")
    private java.lang.String releaseNumber;

    @org.kie.api.definition.type.Label("Transaction code")
    private java.lang.String transactionCode;

    @org.kie.api.definition.type.Label("Transaction Count")
    private int transactionCount;

    @org.kie.api.definition.type.Label("Provider ID")
    private java.lang.String providerId;

    @org.kie.api.definition.type.Label(value = "ActionsToPerform")
    private java.util.List<java.lang.String> actions;

    public CreditRequest() {
    }

    public java.lang.String getBIN() {
        return this.BIN;
    }

    public void setBIN(java.lang.String BIN) {
        this.BIN = BIN;
    }

    public java.lang.String getReleaseNumber() {
        return this.releaseNumber;
    }

    public void setReleaseNumber(java.lang.String releaseNumber) {
        this.releaseNumber = releaseNumber;
    }

    public java.lang.String getTransactionCode() {
        return this.transactionCode;
    }

    public void setTransactionCode(java.lang.String transactionCode) {
        this.transactionCode = transactionCode;
    }

    public int getTransactionCount() {
        return this.transactionCount;
    }

    public void setTransactionCount(int transactionCount) {
        this.transactionCount = transactionCount;
    }

    public java.lang.String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(java.lang.String providerId) {
        this.providerId = providerId;
    }

    public java.util.List<java.lang.String> getActions() {
        return this.actions;
    }

    public void setActions(java.util.List<java.lang.String> actions) {
        this.actions = actions;
    }

    public CreditRequest(java.lang.String BIN, java.lang.String releaseNumber,
                         java.lang.String transactionCode, int transactionCount,
                         java.lang.String providerId,
                         java.util.List<java.lang.String> actions) {
        this.BIN = BIN;
        this.releaseNumber = releaseNumber;
        this.transactionCode = transactionCode;
        this.transactionCount = transactionCount;
        this.providerId = providerId;
        this.actions = actions;
    }

}